version: '3.8'
services:
  ages-db:
    image: postgres:16
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Jakarta
    networks:
      madnessnet:
        ipv4_address: 172.30.0.3
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  madnessnet:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 172.30.0.0/24
volumes:
  postgres:
